### ISSUE TITLE
Not working with active record relations

### ISSUE THREAD

**Issue by dkumar431** [sgringwe/knockoff#7]
After getting frustrated with octopus, octoshark, db-charmer, makara finally I found you gem. But this gem too have the same issue. I configured everything as per your suggestion. I have 2 slaves

For example the below query, selects slave properly,

`Knockoff.on_replica { User.find(1) }`

But the below query is always hitting to the master,

`Knockoff.on_replica { User.where(id: 1) }`

I just need few search queries to hit to our 2 slave database instead of master. We do not need any other features or customisation. So I though your gem would be perfect for that. But still struggling..

I am on Rails 5.

**Comment by sgringwe** [comment]
@dkumar431 Interesting. This may be because in `Knockoff.on_replica { User.where(id: 1) }` you are only building a relation, not executing the query. What happens if you try `Knockoff.on_replica { User.where(id: 1).to_a }`?

**Comment by dkumar431** [comment]
Adding `.to_a` to the query working with octopus but not with knockoff.

**Comment by sgringwe** [comment]
I just merged https://github.com/sgringwe/knockoff/pull/8 which seems to show that it's working as expected. Can you open a PR with a failing test?
